[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[functions]
  directory = "functions-build"

# Define scheduled function with cron schedule
[functions.scheduled-processor]
  schedule = "*/15 * * * *"

# No special configuration needed for webhook function
# It is automatically included based on the file name

[dev]
  autoLaunch = false 