[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[functions]
  directory = "functions-build"

# Scheduled function removed - audio processing is now triggered directly from Sacral Track app
# Old schedule was: "*/15 * * * *" (every 15 minutes)

# No special configuration needed for webhook function
# It is automatically included based on the file name

[dev]
  autoLaunch = false 